version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - transport.host=127.0.0.1
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With, Content-Type, Content-Length, Access-Control-Allow-Headers, Authorization
    ports:
      - "9200:9200"
  frontend:
    build: .
    ports:
      - "3000:3000"
    container_name: frontend
